[common]
10.0.1.10 ansible_user=ubuntu

[webservers]
web01.dev.local ansible_host=10.0.1.20
web02.dev.local ansible_host=10.0.1.21

[databases]
db01.dev.local ansible_host=10.0.1.30

[dev:children]
webservers
databases