---
- name: Apply Base System Configurations and Security Hardening
  hosts: all
  become: true
  tasks:
    - name: Update apt cache and upgrade packages / Actualizar sistema
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Install common essential packages / Instalar utilidades esenciales
      ansible.builtin.apt:
        name:
          - curl
          - git
          - htop
          - ufw
          - unzip
        state: present

    - name: Set system timezone / Ajustar zona horaria
      community.general.timezone:
        name: "{{ time_zone }}"