apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-replicaset
  namespace: devops-app
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: web-app
        image: nginx:alpine
        ports:
        - containerPort: 80